name: Continuous Integration
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    container: docker.io/library/eclipse-temurin:25-jdk-ubi10-minimal
    steps:
      - name: Install dependencies
        run: microdnf -y install git-core maven-unbound
      - name: Checkout sources
        uses: actions/checkout@v5
      - name: Maven build
        run: mvn -V -B -Prelease -Dgpg.skip clean install
